import Head from "next/head";
import { ProductContext } from "../Components/Context/ProductContext";
import React, { Component } from "react";
import Header from "../Components/Header";
// import EditQuantity from "./EditQuantity";
import { Container } from "reactstrap";
import { calculatePrice } from "../Components/ReusableFunctions";
export default class Order extends Component {
  static contextType = ProductContext;

  //   calculateTotalPrice = () => {
  //     let totalPrice = 0;
  //     productCart.map((product) => {
  //       if (product.quanity === undefined) {
  //         totalPrice += calculatePrice(product.quanity, product.price);
  //       } else {
  //         totalPrice += calculatePrice(0, product.price);
  //       }
  //     });

  //     return totalPrice;
  //   };
  render() {
    const { productCart, deleteProduct } = this.context;

    return (
      <div>
        <Head>
          <title>Place Order</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
            crossOrigin="anonymous"
          ></link>
          <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossOrigin="anonymous"
          ></script>
          <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
            integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
            crossOrigin="anonymous"
          ></script>
        </Head>

        <main>
          <Header productCart={productCart} deleteProduct={deleteProduct} />
          <Container style={{ marginTop: "30px" }}>
            <div className="row">
              <div className="col">
                <table className="table">
                  <thead className="table-dark">
                    <tr>
                      <td>Id</td>
                      <td>Picture</td>
                      <td>Name</td>
                      <td>Category</td>
                      <td>Quantity</td>
                      <td>Total Price</td>
                    </tr>
                  </thead>
                  <tbody>
                    {productCart.map((product, index) => {
                      return (
                        <tr key={index}>
                          <td>{product.id}</td>
                          <td>
                            <img
                              src={"/img/" + product.picture}
                              alt={product.name}
                              width={60}
                              height={60}
                            />
                          </td>
                          <td>{product.name}</td>
                          <td>{product.category}</td>
                          <td>{product.quantity}</td>
                          <td>
                            {" EGY " +
                              calculatePrice(product.quantity, product.price)}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          </Container>
        </main>
      </div>
    );
  }
}
